export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const FETCHING_MOVIES_SUCESS = 'FETCHING_MOVIES_SUCESS';
export const FETCHING_MOVIES_FAILURE = 'FETCHING_MOVIES_FAILURE';
export const FILTERING_MOVIE_NAME = 'FILTERING_MOVIE_NAME';
export const REVERT_MOVIE_DATA = 'REVERT_MOVIE_DATA';
